server:
  port: 80
spring:
  security:
    user:
      name: user
      password: 123
  datasource:
    url: jdbc:mysql://localhost:3306/schema_name?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wangsl.domain
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
